### ISSUE TITLE
Use CHAN_SS7 + MTPD3

### ISSUE THREAD

**Issue by DanielRwx** [sipgate/homer#1]
Hello!, is possible to use SIPCAPTURE to mirror ASTERISK + CHAN_SS7 (https://www.netfors.com/chan_ss7/)  and MTP3 packets to homer?

**Comment by vinzens** [comment]
Hi, the captagent is supposed to trace signtran SS7 ISUP traffic. As long as the traffic uses this way it is possible to capture traffic from any system. It is not possible to put it into the asterisk like a module.

so the answer is no. MTP3 traffic cannot be captured by captagent.
